### ISSUE TITLE
user agent does not loads in python lesser than 3.6 

### ISSUE THREAD

**Issue by HusnainAslam** [Luqman-Ud-Din/random_user_agent#1]
```
>>> from random_user_agent.user_agent import UserAgent
>>> user_agent_rotator = UserAgent(software_names=['chrome'], operating_systems=['windows', 'linux'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/random_user_agent/user_agent.py", line 23, in __init__
    for user_agent in self.load_user_agents():
  File "/usr/local/lib/python3.5/dist-packages/random_user_agent/user_agent.py", line 49, in load_user_agents
    return json.loads(user_agents)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by Luqman-Ud-Din** [comment]
Thanks @HusnainAslam
